import type { Metadata } from "next";
import "./globals.css";
import Trailer from "./components/Trailer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        {/* Main content will share space with Trailer */}
        <main className="flex-grow overflow-auto">{children}</main>
        {/* Trailer will always be visible at the bottom */}
        <Trailer />
      </body>
    </html>
  );
}